### ISSUE TITLE
GMC crashes on block submision

### ISSUE THREAD

**Issue by zet-tech** [Musicoin/go-musicoin#32]
Hi,

Recently we have found out on our pool that sometimes when our software (open ethereum pool) tries to insert new block, GMC creases with the following error. According to our logs this started to happen after migration to v1.1.0 (very rarely), and today (29 Aug) it happened over 10 times. Now we migrate to v1.5.0 but please check that bug is fixed in future releases.

#### System information

Geth version:v1.1.0
OS & Version: Linux
Commit hash : (if `develop`) -

#### Expected behaviour

Block inserted into blockchain

#### Actual behaviour

GMC crashes with status code 2/INVALIDARGUMENT

#### Steps to reproduce the behaviour

unknown

#### Backtrace

````
sie 29 12:35:27 mc-node.service: Unit entered failed state.
sie 29 12:35:27 mc-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
sie 29 12:35:27 os/signal.signal_recv(0x0)
sie 29 12:35:27 goroutine 25 [syscall, 182 minutes]:
sie 29 12:35:27         /ext-go/3/src/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x1a2
sie 29 12:35:27 created by github.com/rjeczalik/notify.newNonrecursiveTree
sie 29 12:35:27         /ext-go/3/src/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x94
sie 29 12:35:27 github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc420072300, 0xc4200722a0)
sie 29 12:35:27 goroutine 23 [chan receive, 182 minutes]:
sie 29 12:35:27         /ext-go/3/src/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x176
sie 29 12:35:27 created by github.com/rjeczalik/notify.newNonrecursiveTree
sie 29 12:35:27         /ext-go/3/src/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0x5a
sie 29 12:35:27 github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc420072300, 0xc420072240)
sie 29 12:35:27 goroutine 22 [chan receive, 182 minutes]:
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:460 +0x83
sie 29 12:35:27 created by github.com/ethereum/go-ethereum/logger/glog.init.1
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:931 +0x7a
sie 29 12:35:27 github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x1567b40)
sie 29 12:35:27 goroutine 21 [chan receive]:
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/logger/sys.go:60 +0x35
sie 29 12:35:27 created by github.com/ethereum/go-ethereum/logger.init.1
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/logger/sys.go:81 +0x621
sie 29 12:35:27 github.com/ethereum/go-ethereum/logger.dispatchLoop()
sie 29 12:35:27 goroutine 20 [select]:
sie 29 12:35:27         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
sie 29 12:35:27 runtime.goexit()
sie 29 12:35:27 goroutine 17 [syscall, 182 minutes, locked to thread]:
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/cmd/gmc/main.go:240 +0x55
sie 29 12:35:27 main.main()
sie 29 12:35:27         /ext-go/3/src/gopkg.in/urfave/cli.v1/app.go:241 +0x560
sie 29 12:35:27 gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420083680, 0xc420082000, 0x18, 0x18, 0x0, 0x0)
sie 29 12:35:27         /ext-go/3/src/gopkg.in/urfave/cli.v1/app.go:480 +0x198
sie 29 12:35:27 gopkg.in/urfave/cli%2ev1.HandleAction(0xc30b40, 0xe2f188, 0xc4202f6f00, 0x0, 0x0)
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:302 +0xa4
sie 29 12:35:27 reflect.Value.Call(0xc30b40, 0xe2f188, 0x13, 0xc420127d20, 0x1, 0x1, 0x7, 0x0, 0xc4202dd700)
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:434 +0x91f
sie 29 12:35:27 reflect.Value.call(0xc30b40, 0xe2f188, 0x13, 0xd4e3b7, 0x4, 0xc420127d20, 0x1, 0x1, 0xc420127ca8, 0xd361a0, ...)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/cmd/gmc/main.go:272 +0xee
sie 29 12:35:27 main.gmc(0xc4202f6f00, 0x0, 0x0)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/node/node.go:492 +0x8b
sie 29 12:35:27 github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc420118500)
sie 29 12:35:27 goroutine 1 [chan receive, 182 minutes]:
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:2668 +0x2ce
sie 29 12:35:27 created by net/http.(*Server).Serve
sie 29 12:35:27         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc44831dfd0 sp=0xc44831dfc8
sie 29 12:35:27 runtime.goexit()
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1825 +0x612 fp=0xc44831dfc8 sp=0xc44831dd58
sie 29 12:35:27 net/http.(*conn).serve(0xc4228c6140, 0x14b27c0, 0xc420507200)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:2568 +0x92 fp=0xc44831dd58 sp=0xc44831dd10
sie 29 12:35:27 net/http.serverHandler.ServeHTTP(0xc4200bdc30, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc44831dd10 sp=0xc44831dce8
sie 29 12:35:27 net/http.HandlerFunc.ServeHTTP(0xc4225dc620, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/3/src/github.com/rs/cors/cors.go:122 +0xe9 fp=0xc44831dce8 sp=0xc44831dc90
sie 29 12:35:27 github.com/rs/cors.(*Cors).Handler.func1(0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc44831dc90 sp=0xc44831dc68
sie 29 12:35:27 net/http.HandlerFunc.ServeHTTP(0xc4224ff940, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/http.go:121 +0x378 fp=0xc44831dc68 sp=0xc44831dba8
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.newJSONHTTPHandler.func1(0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:235 +0x4e fp=0xc44831dba8 sp=0xc44831db60
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc4225be3c0, 0x14b66e0, 0xc430030f50, 0x1)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:211 +0x3ee fp=0xc44831db60 sp=0xc44831da20
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc4225be3c0, 0x14b66e0, 0xc430030f50, 0x858901, 0x1, 0x0, 0x0)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:345 +0x1ba fp=0xc44831da20 sp=0xc44831d9a0
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4225be3c0, 0x14b3080, 0xc422b844c0, 0x14b66e0, 0xc430030f50, 0xc429ef
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x768 fp=0xc44831d9a0 sp=0xc44831d7e0
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4225be3c0, 0x14b3080, 0xc422b844c0, 0x14b66e0, 0xc430030f50, 0xc429
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc44831d7e0 sp=0xc44831d778
sie 29 12:35:27 reflect.Value.Call(0xc4328e3500, 0xc42000f7d8, 0x13, 0xc430031040, 0x3, 0x3, 0x2, 0x2, 0xc42259bb00)
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:434 +0x91f fp=0xc44831d778 sp=0xc44831d430
sie 29 12:35:27 reflect.Value.call(0xc4328e3500, 0xc42000f7d8, 0x13, 0xd4e3b7, 0x4, 0xc430031040, 0x3, 0x3, 0x20, 0xc42259bb00, ...)
sie 29 12:35:27         /usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc44831d430 sp=0xc44831d3e0
sie 29 12:35:26 runtime.call64(0xc422802bd0, 0xc42000f7d8, 0xc4289cda70, 0x1800000030)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/eth/api.go:573 +0x5a fp=0xc44831d3e0 sp=0xc44831d328
sie 29 12:35:26 github.com/ethereum/go-ethereum/eth.(*PublicBlockChainAPI).GetBlockByNumber(0xc432988730, 0xfffffffffffffffe, 0x0, 0x0, 0x0
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/eth/api.go:64 +0x89 fp=0xc44831d328 sp=0xc44831d300
sie 29 12:35:26 github.com/ethereum/go-ethereum/eth.blockByNumber(0xc432aea8a0, 0xc4201f85a0, 0xfffffffffffffffe, 0xc4289cda70)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/miner/miner.go:169 +0x2f fp=0xc44831d300 sp=0xc44831d2d8
sie 29 12:35:26 github.com/ethereum/go-ethereum/miner.(*Miner).Pending(0xc432aea8a0, 0xc44efb9100, 0xbba17d)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/miner/worker.go:174 +0x153 fp=0xc44831d2d8 sp=0xc44831d268
sie 29 12:35:26 github.com/ethereum/go-ethereum/miner.(*worker).pending(0xc4201f86c0, 0x0, 0x0)
sie 29 12:35:27 reflect.Value.call(0xc30b40, 0xe2f188, 0x13, 0xd4e3b7, 0x4, 0xc420127d20, 0x1, 0x1, 0xc420127ca8, 0xd361a0, ...)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/cmd/gmc/main.go:272 +0xee
sie 29 12:35:27 main.gmc(0xc4202f6f00, 0x0, 0x0)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/node/node.go:492 +0x8b
sie 29 12:35:27 github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc420118500)
sie 29 12:35:27 goroutine 1 [chan receive, 182 minutes]:
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:2668 +0x2ce
sie 29 12:35:27 created by net/http.(*Server).Serve
sie 29 12:35:27         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc44831dfd0 sp=0xc44831dfc8
sie 29 12:35:27 runtime.goexit()
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1825 +0x612 fp=0xc44831dfc8 sp=0xc44831dd58
sie 29 12:35:27 net/http.(*conn).serve(0xc4228c6140, 0x14b27c0, 0xc420507200)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:2568 +0x92 fp=0xc44831dd58 sp=0xc44831dd10
sie 29 12:35:27 net/http.serverHandler.ServeHTTP(0xc4200bdc30, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc44831dd10 sp=0xc44831dce8
sie 29 12:35:27 net/http.HandlerFunc.ServeHTTP(0xc4225dc620, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/3/src/github.com/rs/cors/cors.go:122 +0xe9 fp=0xc44831dce8 sp=0xc44831dc90
sie 29 12:35:27 github.com/rs/cors.(*Cors).Handler.func1(0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc44831dc90 sp=0xc44831dc68
sie 29 12:35:27 net/http.HandlerFunc.ServeHTTP(0xc4224ff940, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/http.go:121 +0x378 fp=0xc44831dc68 sp=0xc44831dba8
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.newJSONHTTPHandler.func1(0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:235 +0x4e fp=0xc44831dba8 sp=0xc44831db60
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc4225be3c0, 0x14b66e0, 0xc430030f50, 0x1)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:211 +0x3ee fp=0xc44831db60 sp=0xc44831da20
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc4225be3c0, 0x14b66e0, 0xc430030f50, 0x858901, 0x1, 0x0, 0x0)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:345 +0x1ba fp=0xc44831da20 sp=0xc44831d9a0
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4225be3c0, 0x14b3080, 0xc422b844c0, 0x14b66e0, 0xc430030f50, 0xc429ef
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x768 fp=0xc44831d9a0 sp=0xc44831d7e0
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4225be3c0, 0x14b3080, 0xc422b844c0, 0x14b66e0, 0xc430030f50, 0xc429
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc44831d7e0 sp=0xc44831d778
sie 29 12:35:27 reflect.Value.Call(0xc4328e3500, 0xc42000f7d8, 0x13, 0xc430031040, 0x3, 0x3, 0x2, 0x2, 0xc42259bb00)
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:434 +0x91f fp=0xc44831d778 sp=0xc44831d430
sie 29 12:35:27 reflect.Value.call(0xc4328e3500, 0xc42000f7d8, 0x13, 0xd4e3b7, 0x4, 0xc430031040, 0x3, 0x3, 0x20, 0xc42259bb00, ...)
sie 29 12:35:27         /usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc44831d430 sp=0xc44831d3e0
sie 29 12:35:26 runtime.call64(0xc422802bd0, 0xc42000f7d8, 0xc4289cda70, 0x1800000030)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/eth/api.go:573 +0x5a fp=0xc44831d3e0 sp=0xc44831d328
sie 29 12:35:26 github.com/ethereum/go-ethereum/eth.(*PublicBlockChainAPI).GetBlockByNumber(0xc432988730, 0xfffffffffffffffe, 0x0, 0x0, 0x0
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/eth/api.go:64 +0x89 fp=0xc44831d328 sp=0xc44831d300
sie 29 12:35:26 github.com/ethereum/go-ethereum/eth.blockByNumber(0xc432aea8a0, 0xc4201f85a0, 0xfffffffffffffffe, 0xc4289cda70)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/miner/miner.go:169 +0x2f fp=0xc44831d300 sp=0xc44831d2d8
sie 29 12:35:26 github.com/ethereum/go-ethereum/miner.(*Miner).Pending(0xc432aea8a0, 0xc44efb9100, 0xbba17d)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/miner/worker.go:174 +0x153 fp=0xc44831d2d8 sp=0xc44831d268
sie 29 12:35:26 github.com/ethereum/go-ethereum/miner.(*worker).pending(0xc4201f86c0, 0x0, 0x0)
sie 29 12:35:27 reflect.Value.call(0xc30b40, 0xe2f188, 0x13, 0xd4e3b7, 0x4, 0xc420127d20, 0x1, 0x1, 0xc420127ca8, 0xd361a0, ...)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/cmd/gmc/main.go:272 +0xee
sie 29 12:35:27 main.gmc(0xc4202f6f00, 0x0, 0x0)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/node/node.go:492 +0x8b
sie 29 12:35:27 github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc420118500)
sie 29 12:35:27 goroutine 1 [chan receive, 182 minutes]:
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:2668 +0x2ce
sie 29 12:35:27 created by net/http.(*Server).Serve
sie 29 12:35:27         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc44831dfd0 sp=0xc44831dfc8
sie 29 12:35:27 runtime.goexit()
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1825 +0x612 fp=0xc44831dfc8 sp=0xc44831dd58
sie 29 12:35:27 net/http.(*conn).serve(0xc4228c6140, 0x14b27c0, 0xc420507200)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:2568 +0x92 fp=0xc44831dd58 sp=0xc44831dd10
sie 29 12:35:27 net/http.serverHandler.ServeHTTP(0xc4200bdc30, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc44831dd10 sp=0xc44831dce8
sie 29 12:35:27 net/http.HandlerFunc.ServeHTTP(0xc4225dc620, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/3/src/github.com/rs/cors/cors.go:122 +0xe9 fp=0xc44831dce8 sp=0xc44831dc90
sie 29 12:35:27 github.com/rs/cors.(*Cors).Handler.func1(0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc44831dc90 sp=0xc44831dc68
sie 29 12:35:27 net/http.HandlerFunc.ServeHTTP(0xc4224ff940, 0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/http.go:121 +0x378 fp=0xc44831dc68 sp=0xc44831dba8
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.newJSONHTTPHandler.func1(0x14b18c0, 0xc45d474c40, 0xc44897c100)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:235 +0x4e fp=0xc44831dba8 sp=0xc44831db60
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc4225be3c0, 0x14b66e0, 0xc430030f50, 0x1)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:211 +0x3ee fp=0xc44831db60 sp=0xc44831da20
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc4225be3c0, 0x14b66e0, 0xc430030f50, 0x858901, 0x1, 0x0, 0x0)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:345 +0x1ba fp=0xc44831da20 sp=0xc44831d9a0
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4225be3c0, 0x14b3080, 0xc422b844c0, 0x14b66e0, 0xc430030f50, 0xc429ef9110)
sie 29 12:35:27         /ext-go/1/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x768 fp=0xc44831d9a0 sp=0xc44831d7e0
sie 29 12:35:27 github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4225be3c0, 0x14b3080, 0xc422b844c0, 0x14b66e0, 0xc430030f50, 0xc429ef9110, 0x3, 0xc44a201784, 0x10)
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc44831d7e0 sp=0xc44831d778
sie 29 12:35:27 reflect.Value.Call(0xc4328e3500, 0xc42000f7d8, 0x13, 0xc430031040, 0x3, 0x3, 0x2, 0x2, 0xc42259bb00)
sie 29 12:35:27         /usr/local/go/src/reflect/value.go:434 +0x91f fp=0xc44831d778 sp=0xc44831d430
sie 29 12:35:27 reflect.Value.call(0xc4328e3500, 0xc42000f7d8, 0x13, 0xd4e3b7, 0x4, 0xc430031040, 0x3, 0x3, 0x20, 0xc42259bb00, ...)
sie 29 12:35:27         /usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc44831d430 sp=0xc44831d3e0
sie 29 12:35:26 runtime.call64(0xc422802bd0, 0xc42000f7d8, 0xc4289cda70, 0x1800000030)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/eth/api.go:573 +0x5a fp=0xc44831d3e0 sp=0xc44831d328
sie 29 12:35:26 github.com/ethereum/go-ethereum/eth.(*PublicBlockChainAPI).GetBlockByNumber(0xc432988730, 0xfffffffffffffffe, 0x0, 0x0, 0x0, 0x0)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/eth/api.go:64 +0x89 fp=0xc44831d328 sp=0xc44831d300
sie 29 12:35:26 github.com/ethereum/go-ethereum/eth.blockByNumber(0xc432aea8a0, 0xc4201f85a0, 0xfffffffffffffffe, 0xc4289cda70)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/miner/miner.go:169 +0x2f fp=0xc44831d300 sp=0xc44831d2d8
sie 29 12:35:26 github.com/ethereum/go-ethereum/miner.(*Miner).Pending(0xc432aea8a0, 0xc44efb9100, 0xbba17d)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/miner/worker.go:174 +0x153 fp=0xc44831d2d8 sp=0xc44831d268
sie 29 12:35:26 github.com/ethereum/go-ethereum/miner.(*worker).pending(0xc4201f86c0, 0x0, 0x0)
sie 29 12:35:26         /ext-go/1/src/github.com/ethereum/go-ethereum/core/state/statedb.go:469 +0x3d1 fp=0xc44831d268 sp=0xc44831d010
sie 29 12:35:26 github.com/ethereum/go-ethereum/core/state.(*StateDB).Copy(0xc4221d3d10, 0x0)
sie 29 12:35:26         /usr/local/go/src/runtime/hashmap.go:727 +0x2b3 fp=0xc44831d010 sp=0xc44831cfb8
sie 29 12:35:26 runtime.mapiterinit(0xc594c0, 0xc42aabbc20, 0xc44831d1f8)
sie 29 12:35:26         /usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc44831cfb8 sp=0xc44831cf08
sie 29 12:35:26 runtime.mapiternext(0xc44831d1f8)
sie 29 12:35:26         /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc44831cf08 sp=0xc44831cee8
sie 29 12:35:26 runtime.throw(0xd96b8f, 0x26)
sie 29 12:35:26 goroutine 178 [running]:
sie 29 12:35:26 fatal error: concurrent map iteration and map write
sie 29 12:35:26 I0829 12:35:26.030823 miner/worker.go:539] commit new work on block 978004 with 26 txs & 0 uncles. Took 20.570913ms
sie 29 12:35:26 I0829 12:35:26.010151 core/blockchain.go:1001] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 6.407717ms. #978003 [45c44fa7 / 45c44fa7]
sie 29 12:35:18 I0829 12:35:18.677510 miner/worker.go:539] commit new work on block 978003 with 21 txs & 0 uncles. Took 6.429666ms
sie 29 12:35:18 I0829 12:35:18.671014 core/blockchain.go:1001] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 6.004749ms. #978002 [8faad153 / 8faad153]

````

**Comment by immartian** [comment]
which build you were using?

**Comment by etherninja** [comment]
Same issue. It happens a couple times a day. I was using the standard release binary, but have recompiled with go1.7.1. See if it happens there

**Comment by immartian** [comment]
How about Go 1.6x?

**Comment by zet-tech** [comment]
This happens on both recent releases (v1.1.0 and v1.5.0). We use build provided in Releases section on GitHub.

Please fix this issue ASAP because it makes mining very unstable.

@etherninja any resolution to this problem using GMC recompiled with different go version?

We will try moving back to v1.0.1 and report progress.

@immartian Somewhere on github I read that you use Parity on MC Orbiter. Is it possible to use it for mining as a temporary workaround for this issue?

**Comment by immartian** [comment]
received several report on crashing with different reasons. 
We need to make a thorough investigation on different Go versions(mostly the problem come from). 

For Parity, yes, it's stabler for this version of blockchain, but we are going to make big change in next version. So won't be able to support Parity any more.

**Comment by zet-tech** [comment]
Can you provide config .json file for Parity ?

We are currently loosing 1/3 of our blocks and orphan rate is still increasing.

**Comment by immartian** [comment]
under https://github.com/Musicoin/orbiter https://github.com/Musicoin/orbiter/blob/master/mc.json (under Parity 1.5) and https://github.com/Musicoin/orbiter/blob/master/mc_parity16.json  (1.6+)

**Comment by trgava** [comment]
Using 1.5.0 compiled from source (Ubuntu 16.04LTS default Go). No problems.

**Comment by etherninja** [comment]
I have not seen an issue with the release compiled from source as of yet. I seems to be an issue with pre-compile release v1.5.0.

**Comment by frankurcrazy** [comment]
I've also have the same issue with the binary release of GMC v1.5.0.  But after I compiled from source with go 1.6.2, the problem's gone for now.

**Comment by immartian** [comment]
The binary release used Go 1.7.3, need to check if there introduced any new memory leaks from other communities.

**Comment by zet-tech** [comment]
Are you sure Go 1.7.3 ? 
$ gmc version
GMC
Version: 1.5.0-stable-c937d2e6
Protocol Versions: [63 62]
Network Id: 7762959
Go Version: go1.8.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

The problem was caused by Go developers. They introduced more strict validation of concurrency errors (especially read write race error) in application code that cause GMC crashes. Iin previous Go versions those errors are logged as warning or ignored, now they cause fatal errors resulting in application crash. As temporal solution we all can compile GMC using old Go version. But for future development those concurrency errors in GMC code should be fixed.

I also confirm that Parity 1.6.10 as workaround works pretty well for mining.

**Comment by immartian** [comment]
@zet-tech let's have chat in slack, I wonder if there are some other issues we can collaborate.

**Comment by Varunram** [comment]
There's a problem with Go1.8 which is still open (directory structure was made stricter), so for the time being, please use Go1.7 and lower and it should work fine. Worst case, Go1.6 should work as mentioned earlier in the thread.

**Comment by immartian** [comment]
@zet-tech I found the reason of Go version check because when we build with `make gmc-cross", it goes to docker instead of using local golang compiler. We will build with 1.7.3 for the upcoming release though.

**Comment by immartian** [comment]
Hi guys, please help test new release of GMC on different platform. I have configured with Go 1.7.3 and all should be smoother this time, if you can help validate. Thanks and close this by now.
