### ISSUE TITLE
command to send fubd from pool wallet to external online wallet 

### ISSUE THREAD

**Issue by bapparabi** [Musicoin/go-musicoin#52]
what is command to send fund available from pool wallet to external wallet

**Comment by bapparabi** [comment]
i am trying to sedn to musiccoin.org wallet 

invalid address
    at web3.js:3887:15
    at web3.js:3713:20
    at web3.js:4939:28
    at web3.js:4938:12
    at web3.js:4964:18
    at web3.js:4989:23
    at <anonymous>:1:1

**Comment by bapparabi** [comment]
eth.sendTransaction({from:eth.accounts[0xaf2770026a6b8999149b640871b0400e53c5f733], to: "0x325e8a67db242341a2b65bf0524566c34d3c26f7" , value: web3.toWei(851.5, "ether")})
